CREATE DATABASE `nagios` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'ndoutils'@'localhost' IDENTIFIED BY 'n@gweb';

GRANT USAGE ON * . * TO 'ndoutils'@'localhost' IDENTIFIED BY 'n@gweb' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON `nagios` . * TO 'ndoutils'@'localhost' WITH GRANT OPTION ;
