redirect 	301	/1001-animals-to-spot/p/BK-ANISPOT/	http://www.hometrainingtools.com/science-books/c/202/action/showall/
redirect 	301	/1001-bugs-to-spot/p/BK-BUGSPOT/	http://www.hometrainingtools.com/science-books/c/202/action/showall/
redirect 	301	/101-facts-about-science-quiz-book/p/BK-10..	http://www.hometrainingtools.com/101-facts-about-science-quiz-book/p/BK-101FACT/
redirect 	301	/10-megapixel-m	http://www.hometrainingtools.com/digital-microscopes-and-cameras/c/129/action/showall/
redirect 	301	/150-captivating-chemistry-experiments	http://www.hometrainingtools.com/150-captivating-chemistry-experiments/p/BK-CHEMEXP/
redirect 	301	/3d-elements	http://www.hometrainingtools.com/3d-elements-chart/p/CM-PELEM3D/
redirect 	301	/8467/a/8467/	http://www.hometrainingtools.com/newsletter-archives/a/8467/
redirect 	301	/a..	http://www.hometrainingtools.com/a/designing-a-science-fair-project-teaching-tip/
redirect 	301	/ABeka-Kits	http://www.hometrainingtools.com/kits-for-a-beka-curriculum/c/48/
redirect 	301	/about-apologia	http://www.hometrainingtools.com/apologia-curriculum/c/37/
redirect 	301	/about-apologia-science-curric..	http://www.hometrainingtools.com/a/about-apologia-science-curriculum/
redirect 	301	/about-apologia-science-curriculum	http://www.hometrainingtools.com/a/about-apologia-scien
