#!/bin/sh -e

pkgname="nsca-2.9.1"

echo "Installing NSCA..."

# Delete the old archive
rm -rf "$pkgname"

# Extract archive
tar -xzf "$pkgname.tar.gz"

# Make and install 
(
	cd "./$pkgname"
	./configure
	make all
	cp src/nsca /usr/local/nagios/bin
	cp src/send_nsca /usr/local/nagios/libexec
	#cp sample-config/nsca.cfg /usr/local/nagios/etc
	#cp sample-config/send_nsca.cfg /usr/local/nagios/etc
	cp sample-config/nsca.xinetd /etc/xinetd.d/nsca
)

# Restart xinetd
service xinetd restart

# Post-install modifications
./post-install

# Do a simple sanity check to make sure some key files exist...
for f in /usr/local/nagios/bin/nsca /usr/local/nagios/libexec/send_nsca /usr/local/nagios/etc/nsca.cfg ; do
	if [ ! -f "$f" ]; then
		echo "ERROR: NSCA install appears to have failed - exiting.  Missing file = $f"
		exit 1
	fi
done

# Things are okay
echo "NSCA installed OK"

