#!/bin/sh -e

. ../../xi-sys.cfg

echo "NSCA-POST"

# Post-install modifications

# Backup original config files
if [ -f /usr/local/nagios/etc/nsca.cfg ]; then
	cp -f /usr/local/nagios/etc/nsca.cfg /usr/local/nagios/etc/nsca.cfg.orig
fi
if [ -f /usr/local/nagios/etc/send_nsca.cfg ]; then
	cp -f /usr/local/nagios/etc/send_nsca.cfg /usr/local/nagios/etc/send_nsca.cfg.orig
fi

# Config files
cp -r mods/cfg/*.cfg /usr/local/nagios/etc

# Set permissions
chown "$apacheuser:$nagiosgroup" /usr/local/nagios/etc/nsca.cfg
chown "$apacheuser:$nagiosgroup" /usr/local/nagios/etc/send_nsca.cfg

chmod g+rw /usr/local/nagios/etc/nsca.cfg
chmod g+rw /usr/local/nagios/etc/send_nsca.cfg

