#!/bin/sh -e

destdir=/usr/local/nagios/libexec

echo "Installing Extra Plugins..."

cp -r plugins/* "$destdir"
cp -r proy_plugins/*.pl "$destdir"
cp -r rrdtraf-v0.1/check_rrdtraf-v0.1.php "$destdir/check_rrdtraf.php"
cp -r check_rrdtraf-0.5/check_rrdtraf "$destdir"

(
	cd ./check_mysql_health-2.1
	make clean
	./configure
	make
)

cp -r check_mysql_health-2.1/plugins-scripts/check_mysql_health "$destdir"
cp -r check_postgres-2.12.0/check_postgres.pl "$destdir"

# Things are okay
echo "Extra Plugins installed OK"

