#!/bin/sh -e

# Was previous step completed?
if [ ! -f installed.nagiosxi ]; then
	echo "Nagios XI base files were not installed - run previous script" >&2
	exit 1
fi

# Was this step already completed?
if [ -f installed.crontabs ]; then
	echo "Crontabs already configured - skipping."
	exit 0
fi

# Install Nagios XI cron jobs
install -m 644 nagiosxi/nagiosxi.cron.d /etc/cron.d/nagiosxi

echo "Crontabs installed OK"
touch installed.crontabs

