#!/bin/sh -e

. ./xi-sys.cfg

# Was previous step completed?
if [ ! -f installed.chkconfig ]; then
	echo "Daemons were not configured - run previous script" >&2
	exit 1
fi

# Was this step already completed?
if [ -f installed.importnagiosql ]; then
	echo "NagiosQL data already imported - skipping."
	exit
fi

# Stop Apache (workaround for bug where it doesn't create PID file on first start)
# Thought we found root cause (restarting Apache twice in SourceGuardian step)
# but it's still a problem
service "$httpd" stop &>/dev/null
killall httpd || true

# Make sure apache is started
if ! service "$httpd" status &>/dev/null; then
	service "$httpd" start
fi
echo "Sleeping..."
sleep 2
if ! service "$httpd" status &>/dev/null; then
	echo "WARNING: Apache failed to start." >&2
	# echo "ERROR: Apache failed to start - exiting." >&2
	# exit 1
fi

echo "NOTE: If prompted, enter the MySQL root password"

# Check MySQL database (NagiosQL)
if mysql -u root -p"$mysqlpass" nagiosql -e "SELECT COUNT(*) FROM tbl_host" &>/dev/null; then
	echo "NagiosQL database appears OK - continuing..."
else
	echo "ERROR: Cannot connect to NagiosQL database - exiting.  Were MySQL and NagiosQL installed?" >&2
	exit 1
fi

# Check MySQL database
if mysql -u root -p"$mysqlpass" nagios -e "SELECT COUNT(*) FROM nagios_hosts" &>/dev/null; then
	echo "NDOUtils database appears OK - continuing..."
else
	echo "ERROR: Cannot connect to NDOUtils database - exiting.  Was NDOUtils installed?" >&2
	exit 1
fi

# Make sure we have files to import
if [ $(ls /usr/local/nagios/etc/import | wc -l) -eq 0 ]; then
	echo "ERROR: No files to import - exiting.  Were Nagios Core and NagiosQL installed?" >&2
	exit 1
else
	echo "Found config files to import - continuing..."
fi

# Delete temp files
rm -f nagiosxi/basedir/scripts/nagiosql.login
rm -f nagiosxi/basedir/scripts/nagiosql.cookies
rm -f nagiosxi/basedir/scripts/nagiosql.import.monitoring
rm -f nagiosxi/basedir/scripts/nagiosql.export.monitoring

# Nagios Core object definition fixes
cp subcomponents/nagioscore/mods/cfg/fixes/nagiosadmin.cfg /usr/local/nagios/etc/import

# Reconfigure Nagios with initial configuration import
(cd ./nagiosxi/basedir/scripts; ./reconfigure_nagios.sh)

sleep 3

# Make sure all files were imported...
if [ $(ls /usr/local/nagios/etc/import | wc -l) -ne 0 ]; then
	echo "ERROR: NagiosQL import appears to have failed - exiting.  (Reason: Import files are still present in /usr/local/nagios/etc/import)" >&2
	exit 1
fi

# Check Nagios config
if ! service nagios checkconfig &>/dev/null; then
	echo "ERROR: NagiosQL import appears to have failed - exiting.  (Reason: Nagios Core configuration is invalid)" >&2
	exit 1
fi

# Check temp files for clues of success
if grep -q "/nagiosql/index.php?logout=yes" nagiosxi/basedir/scripts/nagiosql.login; then
	echo "Login appears okay"
else
	echo "ERROR: Unable to login to NagiosQL on 'localhost' - exiting. If you have a proxy configured, this may be the cause of the problem." >&2
	exit 1
fi
if grep -q localhost nagiosxi/basedir/scripts/nagiosql.cookies; then
	echo "Cookies appear okay"
else
	echo "ERROR: Unable to get cookies to authenticate against NagiosQL on 'localhost' - exiting.  If you have a proxy configured, this may be the cause of the problem." >&2
	exit 1
fi
if grep -q "successfully inserted" nagiosxi/basedir/scripts/nagiosql.import.monitoring; then
	echo "Import appears okay"
else
	echo "ERROR: Did not find import success messages in NagiosQL output - exiting." >&2
	exit 1
fi
if grep -q "Configuration file successfully written" nagiosxi/basedir/scripts/nagiosql.export.monitoring; then
	echo "Export appears okay"
else
	echo "ERROR: Did not find export success messages in NagiosQL output - exiting." >&2
	exit 1
fi

echo
echo "NagiosQL data imported OK."
touch installed.importnagiosql

