#!/bin/sh -e

. ./xi-sys.cfg

##########################################
# COPY OVER NEW NAGIOS TEMPLATES
##########################################

echo "Installing new XI templates..."

# Copy over static XI templates
cp -r ./subcomponents/nagioscore/mods/cfg/static/* /usr/local/nagios/etc/static

# Copy over XI templates to be imported
cp -r ./subcomponents/nagioscore/mods/cfg/import/* /usr/local/nagios/etc/import
chown "$apacheuser:$nagiosgroup" /usr/local/nagios/etc/import/*.cfg

# Reconfigure Nagios
(
	cd /usr/local/nagiosxi/scripts
	./reconfigure_nagios.sh
)
