#!/bin/sh

# Find a suitable filename
backupfile=/tmp/nagios.crontab.orig
while [ -f "$backupfile" ]; do
	# increment number at the end of the file
	# e.g. /tmp/nagios.crontab.orig   -> /tmp/nagios.crontab.orig.1
	#      /tmp/nagios.crontab.orig.1 -> /tmp/nagios.crontab.orig.2
	backupfile=$(echo "$backupfile" | awk -F. 'BEGIN{OFS="."} {print $1, $2, $3, $4+1}')
done

# Remove old crontab entries
echo "Saving old crontab to $backupfile..."
if [ `crontab -l -u nagios > "$backupfile"` ]; then
    echo "Removing XI cron jobs..."
    crontab -l -u nagios | grep -v /usr/local/nagiosxi/cron | crontab -u nagios -
fi
